### ISSUE TITLE
Turn selection trying to switch to a dead player

### ISSUE THREAD

**Issue by cs716** [apetavern/grubs#386]
Turn selection will sometimes select a dead player and get stuck because it can't get the active worm. Possible related to #385 ?

**Comment by DrewBritt** [comment]
We likely ran into this bug due to what I've fixed with https://github.com/apetavern/grubs/commit/f74ad68856f60cb4664f8eb34f228f57feab5ecf, however I also noticed an oversight in the turn logic that would lead to dead players being selected to play, which I've fixed with https://github.com/apetavern/grubs/commit/417bb9201f97462dcbf86ce00527aa27809d125a.
