### ISSUE TITLE
Adjust nametag text size based on zoom distance

### ISSUE THREAD

**Issue by cs716** [apetavern/grubs#413]
![image](https://github.com/apetavern/grubs/assets/29966072/b0dfb7ee-ce5b-4886-90de-c8240c32a203)
"i love the nametags but i wish the text was a bit bigger when i zoomed out far enough" - Carson

**Comment by CarsonKompon** [comment]
Oh boy I sure do agree with this issue! (Also it should display the HP number inside the bar on both the nametag and the scoreboard on the left). Worms does only the number instead of the bar so it'd be nice to show both so I have context as to what damage numbers actually mean :)
![](https://i.ebayimg.com/images/g/7NYAAOSwMY9d6mP6/s-l1200.webp)
